BEGIN;
	CREATE TABLE local_post_like_undo (
		id UUID PRIMARY KEY,
		post BIGINT NOT NULL REFERENCES post ON DELETE CASCADE,
		person BIGINT NOT NULL REFERENCES person ON DELETE CASCADE
	);

	CREATE TABLE local_reply_like_undo (
		id UUID PRIMARY KEY,
		reply BIGINT NOT NULL REFERENCES reply ON DELETE CASCADE,
		person BIGINT NOT NULL REFERENCES person ON DELETE CASCADE
	);
COMMIT;
