BEGIN;
	CREATE TABLE modlog_event (
		id BIGSERIAL PRIMARY KEY,
		time TIMESTAMPTZ NOT NULL,
		by_community BIGINT REFERENCES community ON DELETE CASCADE,
		by_person BIGINT REFERENCES person,
		action TEXT NOT NULL,
		post BIGINT REFERENCES post ON DELETE CASCADE,
		reply BIGINT REFERENCES reply ON DELETE CASCADE,
		person BIGINT REFERENCES person ON DELETE CASCADE
	);
COMMIT;
